import type { ExamInput, ExamTemplateInput } from "@mockprep/types";

/*
 * Starting exam patterns.
 * ⚠️ Patterns change. Verify every template against the LATEST official notification
 * (SBI, IBPS, SSC, UPSC, NTA) before publishing tests, and edit them in the admin panel.
 */
const min = (m: number) => m * 60;

export const SEED_TEMPLATES: ExamTemplateInput[] = [
  {
    key: "sbi-po-prelims",
    name: "SBI PO Prelims",
    family: "banking",
    skin: "ibps",
    totalTimeSec: min(60),
    optionCount: 5,
    sectionSwitching: "locked_sequential",
    sections: [
      { name: "English Language", count: 30, timeSec: min(20), aliases: ["English"] },
      {
        name: "Quantitative Aptitude",
        count: 35,
        timeSec: min(20),
        aliases: ["Quant", "Numerical Ability", "Data Interpretation"],
      },
      {
        name: "Reasoning Ability",
        count: 35,
        timeSec: min(20),
        aliases: ["Reasoning", "Logical Reasoning"],
      },
    ],
    marking: { correct: 1, wrong: -0.25 },
  },
  {
    key: "ibps-clerk-prelims",
    name: "IBPS Clerk Prelims",
    family: "banking",
    skin: "ibps",
    totalTimeSec: min(60),
    optionCount: 5,
    sectionSwitching: "locked_sequential",
    sections: [
      { name: "English Language", count: 30, timeSec: min(20), aliases: ["English"] },
      {
        name: "Numerical Ability",
        count: 35,
        timeSec: min(20),
        aliases: ["Quantitative Aptitude", "Quant"],
      },
      { name: "Reasoning Ability", count: 35, timeSec: min(20), aliases: ["Reasoning"] },
    ],
    marking: { correct: 1, wrong: -0.25 },
  },
  {
    key: "ssc-cgl-tier1",
    name: "SSC CGL Tier 1",
    family: "ssc",
    skin: "ssc",
    totalTimeSec: min(60),
    optionCount: 4,
    sectionSwitching: "free",
    sections: [
      {
        name: "General Intelligence and Reasoning",
        count: 25,
        aliases: ["Reasoning", "General Intelligence"],
      },
      { name: "General Awareness", count: 25, aliases: ["General Knowledge", "GK", "GA"] },
      { name: "Quantitative Aptitude", count: 25, aliases: ["Quant", "Mathematics", "Maths"] },
      { name: "English Comprehension", count: 25, aliases: ["English", "English Language"] },
    ],
    marking: { correct: 2, wrong: -0.5 },
  },
  {
    key: "upsc-gs1",
    name: "UPSC Prelims GS Paper I",
    family: "upsc",
    skin: "upsc",
    totalTimeSec: min(120),
    optionCount: 4,
    sectionSwitching: "free",
    sections: [{ name: "General Studies", count: 100, aliases: ["GS", "General Studies Paper I"] }],
    // One-third of 2 marks; stored rounded as specified.
    marking: { correct: 2, wrong: -0.66 },
  },
  {
    key: "upsc-csat",
    name: "UPSC Prelims CSAT (Paper II)",
    family: "upsc",
    skin: "upsc",
    totalTimeSec: min(120),
    optionCount: 4,
    sectionSwitching: "free",
    sections: [{ name: "CSAT", count: 80, aliases: ["General Studies Paper II", "Aptitude"] }],
    marking: { correct: 2.5, wrong: -0.83 },
    qualifyingPercent: 33,
  },
  {
    key: "nda-maths",
    name: "NDA Mathematics",
    family: "defence",
    skin: "upsc",
    totalTimeSec: min(150),
    optionCount: 4,
    sectionSwitching: "free",
    sections: [{ name: "Mathematics", count: 120, aliases: ["Maths"] }],
    marking: { correct: 2.5, wrong: -0.83 },
  },
  {
    key: "cds-english",
    name: "CDS English",
    family: "defence",
    skin: "upsc",
    totalTimeSec: min(120),
    optionCount: 4,
    sectionSwitching: "free",
    sections: [{ name: "English", count: 120, aliases: ["English Language"] }],
    marking: { correct: 0.83, wrong: -0.28 },
  },
  {
    key: "jee-main",
    name: "JEE Main Paper 1 (B.E./B.Tech)",
    family: "engineering",
    skin: "nta",
    totalTimeSec: min(180),
    optionCount: 4,
    sectionSwitching: "free",
    sections: [
      { name: "Physics", count: 25, aliases: [] },
      { name: "Chemistry", count: 25, aliases: [] },
      { name: "Mathematics", count: 25, aliases: ["Maths"] },
    ],
    marking: { correct: 4, wrong: -1 },
  },
  {
    key: "custom",
    name: "Custom",
    family: "other",
    skin: "generic",
    totalTimeSec: min(30),
    optionCount: 4,
    sectionSwitching: "free",
    sections: [{ name: "Section 1", count: 20, aliases: [] }],
    marking: { correct: 1, wrong: 0 },
  },
];

export const SEED_EXAMS: ExamInput[] = [
  {
    slug: "sbi-po",
    name: "SBI Probationary Officer (PO)",
    shortName: "SBI PO",
    family: "banking",
    description:
      "Full-length SBI PO Prelims mocks with sectional timers, exactly like the real exam.",
    templateKeys: ["sbi-po-prelims"],
    status: "published",
    sortOrder: 10,
  },
  {
    slug: "ibps-clerk",
    name: "IBPS Clerk",
    shortName: "IBPS Clerk",
    family: "banking",
    description: "IBPS Clerk Prelims mocks with 20-minute sectional timers.",
    templateKeys: ["ibps-clerk-prelims"],
    status: "published",
    sortOrder: 20,
  },
  {
    slug: "ssc-cgl",
    name: "SSC Combined Graduate Level (CGL)",
    shortName: "SSC CGL",
    family: "ssc",
    description: "SSC CGL Tier 1 mocks: 100 questions, 60 minutes.",
    templateKeys: ["ssc-cgl-tier1"],
    status: "published",
    sortOrder: 10,
  },
  {
    slug: "upsc-prelims",
    name: "UPSC Civil Services Prelims",
    shortName: "UPSC Prelims",
    family: "upsc",
    description: "GS Paper I and CSAT (qualifying) mocks.",
    templateKeys: ["upsc-gs1", "upsc-csat"],
    status: "published",
    sortOrder: 10,
  },
  {
    slug: "nda",
    name: "NDA & NA",
    shortName: "NDA",
    family: "defence",
    description: "NDA Mathematics mocks.",
    templateKeys: ["nda-maths"],
    status: "published",
    sortOrder: 10,
  },
  {
    slug: "cds",
    name: "Combined Defence Services (CDS)",
    shortName: "CDS",
    family: "defence",
    description: "CDS English mocks.",
    templateKeys: ["cds-english"],
    status: "published",
    sortOrder: 20,
  },
  {
    slug: "jee-main",
    name: "JEE Main",
    shortName: "JEE Main",
    family: "engineering",
    description: "JEE Main Paper 1 mocks in the NTA interface.",
    templateKeys: ["jee-main"],
    status: "published",
    sortOrder: 10,
  },
];
